<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'category_id' => 1,
                'sku' => 'TANI-001',
                'slug' => 'emamectin-benzoat-lufenuron',
                'name' => 'Emamectin benzoat + lufenuron',
                'short_description' => NULL,
                'description' => 'Mengendalikan ulat grayak, ulat daun, dan penggerek buah. Bekerja cepat sekaligus menghambat perkembangan larva sehingga pengendalian lebih maksimal.',
                'price' => 100000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 2,
                'category_id' => 2,
                'sku' => 'TANI-002',
                'slug' => 'difenoconazole-azoxystrobin',
                'name' => 'Difeconazole+azoxistrobin',
                'short_description' => NULL,
                'description' => 'Fungisida sistemik untuk mengendalikan antraknosa, bercak daun, embun tepung, karat daun, dan berbagai penyakit jamur lainnya.',
                'price' => 80000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'sku' => 'TANI-003',
                'slug' => 'broflanilida',
                'name' => 'Broflanilida',
                'short_description' => NULL,
                'description' => 'Insektisida generasi baru yang efektif mengendalikan ulat, thrips, penggerek, dan hama pengunyah daun lainnya.',
                'price' => 100000,
                'compare_at_price' => NULL,
                'weight_label' => '100 ml',
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'sku' => 'TANI-004',
                'slug' => 'abamectin-bening',
                'name' => 'Abamectin bening',
                'short_description' => NULL,
                'description' => 'Mengendalikan tungau, thrips, kutu daun, dan ulat. Bekerja cepat menghentikan aktivitas makan hama.',
                'price' => 65000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'sku' => 'TANI-005',
                'slug' => 'fipronil',
                'name' => 'Fipronil',
                'short_description' => NULL,
                'description' => 'Mengendalikan wereng, semut, rayap, penggerek batang, dan berbagai hama serangga lainnya.',
                'price' => 50000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 6,
                'category_id' => 2,
                'sku' => 'TANI-006',
                'slug' => 'difenoconazole',
                'name' => 'Difeconazole',
                'short_description' => NULL,
                'description' => 'Fungisida sistemik untuk mengendalikan antraknosa, bercak daun, embun tepung, dan penyakit jamur lainnya.',
                'price' => 70000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 7,
                'category_id' => 2,
                'sku' => 'TANI-007',
                'slug' => 'metalaxyl',
                'name' => 'Metalaxyl',
                'short_description' => NULL,
                'description' => 'Fungisida sistemik untuk mengendalikan busuk akar, rebah semai, busuk batang, dan penyakit akibat jamur tanah.',
                'price' => 80000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 8,
                'category_id' => 3,
                'sku' => 'TANI-008',
                'slug' => 'asam-amino-biostimulant',
                'name' => 'Asam amino Biostimulant + unsur-unsur',
                'short_description' => NULL,
                'description' => 'Membantu mempercepat pertumbuhan tanaman, memperkuat akar, meningkatkan kehijauan daun, dan mengurangi stres tanaman.',
                'price' => 68000,
                'compare_at_price' => NULL,
                'weight_label' => '1000 ml',
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 9,
                'category_id' => 3,
                'sku' => 'TANI-009',
                'slug' => 'hormon-ga3-10000-ppm',
                'name' => 'Hormon GA3 10.000ppm',
                'short_description' => NULL,
                'description' => 'Merangsang pertumbuhan tanaman, pembungaan, pembesaran buah, dan memecah masa dormansi.',
                'price' => 30000,
                'compare_at_price' => NULL,
                'weight_label' => '100 ml',
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 10,
                'category_id' => 3,
                'sku' => 'TANI-010',
                'slug' => 'hormon-auxin-10000-ppm',
                'name' => 'Hormon Auxin 10.000ppm',
                'short_description' => NULL,
                'description' => 'Merangsang pembentukan akar, pertumbuhan tunas, serta mengurangi kerontokan bunga dan buah.',
                'price' => 24000,
                'compare_at_price' => NULL,
                'weight_label' => '100 ml',
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 11,
                'category_id' => 3,
                'sku' => 'TANI-011',
                'slug' => 'hormon-sitokinin-10000-ppm',
                'name' => 'Hormon Sitokinin 10.000ppm',
                'short_description' => NULL,
                'description' => 'Merangsang pembelahan sel, pertumbuhan tunas, dan menjaga daun tetap hijau lebih lama.',
                'price' => 27000,
                'compare_at_price' => NULL,
                'weight_label' => '100 ml',
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 12,
                'category_id' => 3,
                'sku' => 'TANI-012',
                'slug' => 'paclobutrazol-50000-ppm',
                'name' => 'ZPT Paclobutrazol 50.000ppm',
                'short_description' => NULL,
                'description' => 'Membantu merangsang pembungaan dan mengurangi pertumbuhan vegetatif yang berlebihan.',
                'price' => 55000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 13,
                'category_id' => 3,
                'sku' => 'TANI-013',
                'slug' => 'cppu-1000-ppm',
                'name' => 'ZPT CPPU 1000ppm (pembesar buah)',
                'short_description' => NULL,
                'description' => 'Membantu meningkatkan ukuran, bobot, dan kualitas buah.',
                'price' => 30000,
                'compare_at_price' => NULL,
                'weight_label' => '100 ml',
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 14,
                'category_id' => 3,
                'sku' => 'TANI-014',
                'slug' => 'sodium-nitrophenolate-atonik-20-sl',
                'name' => 'ZPT sodium nitrophenolat (atonik)20 SL',
                'short_description' => NULL,
                'description' => 'Perangsang pertumbuhan yang membantu pembentukan akar, tunas, bunga, dan buah.',
                'price' => 70000,
                'compare_at_price' => NULL,
                'weight_label' => '500 ml',
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 15,
                'category_id' => 3,
                'sku' => 'TANI-015',
                'slug' => 'da-6',
                'name' => 'ZPT DA-6 (Dimethil amino hexaonate)',
                'short_description' => NULL,
                'description' => 'Membantu meningkatkan fotosintesis, pertumbuhan akar, pembungaan, dan produktivitas tanaman.',
                'price' => 80000,
                'compare_at_price' => NULL,
                'weight_label' => '500 ml',
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 16,
                'category_id' => 3,
                'sku' => 'TANI-016',
                'slug' => 'triacontanol-1000-ppm',
                'name' => 'Triacontanol 1000ppm',
                'short_description' => NULL,
                'description' => 'Meningkatkan fotosintesis, pertumbuhan tanaman, pembentukan bunga, dan hasil panen.',
                'price' => 35000,
                'compare_at_price' => NULL,
                'weight_label' => '100 ml',
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 17,
                'category_id' => 1,
                'sku' => 'TANI-017',
                'slug' => 'cypermethrin-50-ec',
                'name' => 'Cypermetrin 50EC',
                'short_description' => NULL,
                'description' => 'Insektisida kontak dan lambung dengan efek cepat untuk mengendalikan ulat, kutu, wereng, dan penggerek.',
                'price' => 72000,
                'compare_at_price' => NULL,
                'weight_label' => '500 ml',
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 18,
                'category_id' => 2,
                'sku' => 'TANI-018',
                'slug' => 'pyraclostrobin-100-ec',
                'name' => 'Pyraclostrobin 100EC',
                'short_description' => NULL,
                'description' => 'Fungisida sistemik yang membantu mengendalikan berbagai penyakit jamur sekaligus menjaga kesehatan tanaman.',
                'price' => 82000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 19,
                'category_id' => 2,
                'sku' => 'TANI-019',
                'slug' => 'penconazole-100-ec',
                'name' => 'Penconazole 100EC',
                'short_description' => NULL,
                'description' => 'Fungisida sistemik yang efektif mengendalikan embun tepung, karat daun, dan berbagai penyakit jamur lainnya.',
                'price' => 98000,
                'compare_at_price' => NULL,
                'weight_label' => '250 ml',
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 20,
                'category_id' => 3,
                'sku' => 'TANI-020',
                'slug' => 'brassinolide',
                'name' => 'Brasinolide',
                'short_description' => NULL,
                'description' => 'ZPT premium yang membantu meningkatkan pertumbuhan, pembungaan, pembuahan, serta ketahanan tanaman terhadap stres lingkungan.',
                'price' => 90000,
                'compare_at_price' => NULL,
                'weight_label' => '100 ml',
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'stock' => 100,
                'public_status' => 'active',
                'catalog_status' => 'available',
                'badge_label' => NULL,
                'sold_count' => 0,
                'highlights' => NULL,
                'is_featured' => 0,
                'published_at' => '2026-06-09 08:46:37',
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
        ]);
    }
}
