<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductVariantSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('product_variants')->insert([
            [
                'id' => 1,
                'product_id' => 1,
                'sku' => 'TANI-001-250',
                'label' => '250 ml',
                'price' => 100000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 2,
                'product_id' => 1,
                'sku' => 'TANI-001-500',
                'label' => '500 ml',
                'price' => 190000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 3,
                'product_id' => 1,
                'sku' => 'TANI-001-1000',
                'label' => '1000 ml',
                'price' => 360000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 4,
                'product_id' => 2,
                'sku' => 'TANI-002-250',
                'label' => '250 ml',
                'price' => 80000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 5,
                'product_id' => 2,
                'sku' => 'TANI-002-500',
                'label' => '500 ml',
                'price' => 130000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 6,
                'product_id' => 2,
                'sku' => 'TANI-002-1000',
                'label' => '1000 ml',
                'price' => 245000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 7,
                'product_id' => 3,
                'sku' => 'TANI-003-100',
                'label' => '100 ml',
                'price' => 100000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 8,
                'product_id' => 3,
                'sku' => 'TANI-003-250',
                'label' => '250 ml',
                'price' => 250000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 9,
                'product_id' => 3,
                'sku' => 'TANI-003-500',
                'label' => '500 ml',
                'price' => 495000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 10,
                'product_id' => 4,
                'sku' => 'TANI-004-250',
                'label' => '250 ml',
                'price' => 65000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 11,
                'product_id' => 4,
                'sku' => 'TANI-004-500',
                'label' => '500 ml',
                'price' => 125000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 12,
                'product_id' => 4,
                'sku' => 'TANI-004-1000',
                'label' => '1000 ml',
                'price' => 230000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 13,
                'product_id' => 5,
                'sku' => 'TANI-005-250',
                'label' => '250 ml',
                'price' => 50000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 14,
                'product_id' => 5,
                'sku' => 'TANI-005-500',
                'label' => '500 ml',
                'price' => 90000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 15,
                'product_id' => 5,
                'sku' => 'TANI-005-1000',
                'label' => '1000 ml',
                'price' => 160000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 16,
                'product_id' => 6,
                'sku' => 'TANI-006-250',
                'label' => '250 ml',
                'price' => 70000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 17,
                'product_id' => 6,
                'sku' => 'TANI-006-500',
                'label' => '500 ml',
                'price' => 125000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 18,
                'product_id' => 6,
                'sku' => 'TANI-006-1000',
                'label' => '1000 ml',
                'price' => 235000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 19,
                'product_id' => 7,
                'sku' => 'TANI-007-250',
                'label' => '250 ml',
                'price' => 80000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 20,
                'product_id' => 7,
                'sku' => 'TANI-007-500',
                'label' => '500 ml',
                'price' => 130000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 21,
                'product_id' => 7,
                'sku' => 'TANI-007-1000',
                'label' => '1000 ml',
                'price' => 245000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 22,
                'product_id' => 8,
                'sku' => 'TANI-008-1000',
                'label' => '1000 ml',
                'price' => 68000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 23,
                'product_id' => 9,
                'sku' => 'TANI-009-100',
                'label' => '100 ml',
                'price' => 30000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 24,
                'product_id' => 10,
                'sku' => 'TANI-010-100',
                'label' => '100 ml',
                'price' => 24000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 25,
                'product_id' => 11,
                'sku' => 'TANI-011-100',
                'label' => '100 ml',
                'price' => 27000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 26,
                'product_id' => 12,
                'sku' => 'TANI-012-250',
                'label' => '250 ml',
                'price' => 55000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 27,
                'product_id' => 12,
                'sku' => 'TANI-012-500',
                'label' => '500 ml',
                'price' => 97000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 28,
                'product_id' => 12,
                'sku' => 'TANI-012-1000',
                'label' => '1000 ml',
                'price' => 185000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 29,
                'product_id' => 13,
                'sku' => 'TANI-013-100',
                'label' => '100 ml',
                'price' => 30000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 30,
                'product_id' => 14,
                'sku' => 'TANI-014-500',
                'label' => '500 ml',
                'price' => 70000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 31,
                'product_id' => 14,
                'sku' => 'TANI-014-1000',
                'label' => '1000 ml',
                'price' => 130000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 32,
                'product_id' => 15,
                'sku' => 'TANI-015-500',
                'label' => '500 ml',
                'price' => 80000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 33,
                'product_id' => 15,
                'sku' => 'TANI-015-1000',
                'label' => '1000 ml',
                'price' => 130000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 34,
                'product_id' => 16,
                'sku' => 'TANI-016-100',
                'label' => '100 ml',
                'price' => 35000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 35,
                'product_id' => 16,
                'sku' => 'TANI-016-250',
                'label' => '250 ml',
                'price' => 75000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 36,
                'product_id' => 16,
                'sku' => 'TANI-016-500',
                'label' => '500 ml',
                'price' => 140000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 37,
                'product_id' => 16,
                'sku' => 'TANI-016-1000',
                'label' => '1000 ml',
                'price' => 265000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 4,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 38,
                'product_id' => 17,
                'sku' => 'TANI-017-500',
                'label' => '500 ml',
                'price' => 72000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 39,
                'product_id' => 17,
                'sku' => 'TANI-017-1000',
                'label' => '1000 ml',
                'price' => 135000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 40,
                'product_id' => 18,
                'sku' => 'TANI-018-250',
                'label' => '250 ml',
                'price' => 82000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 41,
                'product_id' => 18,
                'sku' => 'TANI-018-500',
                'label' => '500 ml',
                'price' => 160000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 42,
                'product_id' => 18,
                'sku' => 'TANI-018-1000',
                'label' => '1000 ml',
                'price' => 300000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 43,
                'product_id' => 19,
                'sku' => 'TANI-019-250',
                'label' => '250 ml',
                'price' => 98000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 320,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 44,
                'product_id' => 19,
                'sku' => 'TANI-019-500',
                'label' => '500 ml',
                'price' => 180000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 580,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 2,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 45,
                'product_id' => 19,
                'sku' => 'TANI-019-1000',
                'label' => '1000 ml',
                'price' => 350000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 1100,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 0,
                'is_active' => 1,
                'sort_order' => 3,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
            [
                'id' => 46,
                'product_id' => 20,
                'sku' => 'TANI-020-100',
                'label' => '100 ml',
                'price' => 90000,
                'compare_at_price' => NULL,
                'stock' => 100,
                'weight_grams' => 150,
                'length_cm' => NULL,
                'width_cm' => NULL,
                'height_cm' => NULL,
                'is_default' => 1,
                'is_active' => 1,
                'sort_order' => 1,
                'created_at' => '2026-06-09 08:46:37',
                'updated_at' => '2026-06-09 08:46:37',
            ],
        ]);
    }
}
